// Fill out your copyright notice in the Description page of Project Settings.

#pragma once
#include "NativeGameplayTags.h"

namespace RogueTowerTag
{
	/*Input Tag*/
	ROGUETOWER_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_Move_Forward);
	ROGUETOWER_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_Move_Back);
	ROGUETOWER_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_Move_Left);
	ROGUETOWER_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_Move_Right);
	ROGUETOWER_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_Look);
	ROGUETOWER_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_Dash);
	ROGUETOWER_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_Jump);

	/*Player Tag*/
	ROGUETOWER_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Player_Weapon_GreateSword);
	ROGUETOWER_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Player_Weapon_DualBlade);
	ROGUETOWER_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Player_Weapon_Katana);

	ROGUETOWER_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Player_Ability_Dash);
	ROGUETOWER_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Player_Ability_Jump);
}

