// Fill out your copyright notice in the Description page of Project Settings.

#pragma once
#include "NativeGameplayTags.h"

namespace RogueTowerTag
{
	/*Input Tag*/
	ROGUETOWER_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_Move_Forward);
	ROGUETOWER_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_Move_Back);
	ROGUETOWER_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_Move_Left);
	ROGUETOWER_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_Move_Right);
	ROGUETOWER_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_Look);
	ROGUETOWER_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_Jump);
	ROGUETOWER_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_ComboAttack);

	ROGUETOWER_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_Hold);
	ROGUETOWER_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_Hold_Dash);

	/*Player Tag*/
	ROGUETOWER_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Player_Weapon_GreateSword);
	ROGUETOWER_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Player_Weapon_DualBlade);
	ROGUETOWER_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Player_Weapon_Katana);

	ROGUETOWER_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Player_Ability_Dash);
	ROGUETOWER_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Player_Ability_Jump);
	ROGUETOWER_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Player_Ability_ComboAttack);
	ROGUETOWER_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Player_Ability_ComboAttack_1);
	ROGUETOWER_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Player_Ability_ComboAttack_2);
	ROGUETOWER_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Player_Ability_ComboAttack_3);
	ROGUETOWER_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Player_Ability_ComboAttack_4);
	ROGUETOWER_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Player_Ability_DrawUI);

	ROGUETOWER_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Player_Event_JumpEnd);
	ROGUETOWER_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Player_Event_ComboWindowOpen);
	ROGUETOWER_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Player_Event_ComboWindowClose);

	ROGUETOWER_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Player_Status_Jumpping);
	ROGUETOWER_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Player_Status_ReadyNextCombo);

	/*Shared Tag*/
	ROGUETOWER_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Shared_Event_MeleeHit);
	ROGUETOWER_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Shared_Event_HitReact);

	ROGUETOWER_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Shared_Ability_HitReact);

	/*Enemy Tag*/
	ROGUETOWER_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Enemy_Ability_MeleeAttack);

	ROGUETOWER_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Enemy_Status_Strafing);
}

